# Generated by Django 4.2.3 on 2024-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='comapny',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='so_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
