# Generated by Django 4.2.3 on 2024-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
